// Este enum es como una lista de pasos o reglas que el analizador sigue para entender el código.
// Cada nombre representa una parte diferente de la gramática del lenguaje.
export enum Production {
    PROGRAM,
    BLOCK_USING,
    CLASS,
    BLOCK_MAIN,
    LIST_INSTRUCTIONS,
    LIST_INSTRUCTIONS_P,
    INSTRUCTION,
    DECLARATION,
    TYPE,
    LIST_ID,
    ID_ASIGN,
    ID_ASIGN_P,
    LIST_ID_P,
    ASSIGNATION,
    PRINT,
    INST_IF,
    INST_IF_P,
    INST_FOR,
    FIRST_BLOCK_FOR,
    THIRD_BLOCK_FOR,
    THIRD_BLOCK_FOR_P,
    INCREMENT,
    DECREMENT,
    EXPRESSION,
    ARITHMETIC,
    RELATIONAL,
    ARITHMETIC_P,
    TERM,
    TERM_P,
    FACTOR
}